apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend-service
  labels:
    app: nodejs-backend
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: nodejs-backend
