apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-frontend
  labels:
    app: nextjs-frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-frontend
  template:
    metadata:
      labels:
        app: nextjs-frontend
        tier: frontend
    spec:
      containers:
      - name: nextjs-frontend
        image: ezekiel200483/nextjs-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
