apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-frontend
  namespace: awarri
  labels:
    app: nextjs-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-frontend
  template:
    metadata:
      labels:
        app: nextjs-frontend
    spec:
      containers:
        - name: nextjs-container
          image: 471112961525.dkr.ecr.us-east-1.amazonaws.com/awarri:latest  # Update with your image name and tag
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                secretKeyRef:
                  name: nextjs-secret
                  key: NEXT_PUBLIC_API_URL
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
