---
apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
  namespace: awarri
spec:
  selector:
    app: node-backend
  ports:
    - protocol: TCP
      port: 80   # External port (can be changed)
      targetPort: 4000  # The container’s port
  type: LoadBalancer 