apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  namespace: awarri
  labels:
    app: node-backend
spec:
  replicas: 2  # Adjust replicas based on load
  selector:
    matchLabels:
      app: node-backend
  template:
    metadata:
      labels:
        app: node-backend
    spec:
      containers:
        - name: node-backend
          image: 471112961525.dkr.ecr.us-east-1.amazonaws.com/awarri-backend:latest # Update if using a container registry
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10

